language: objective-c
#xcode_project: DrawingSimulation.xcodeproj
#xcode_scheme: DrawingSimulation

osx_image: xcode7.1

script: 
  - xctool -project DrawingSimulation.xcodeproj -scheme DrawingSimulation -sdk iphonesimulator
